services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 10s

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["bash", "-lc"]
    command: >-
      "ollama pull ${LLM_MODEL} && ollama pull ${EMBED_MODEL} && echo 'Models ready'"
    environment:
      - OLLAMA_HOST=ollama:11434
    volumes:
      - ollama_models:/root/.ollama
    restart: "no"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: ./backend
    container_name: rag-api
    env_file: .env
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_started
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    container_name: rag-web
    env_file: .env
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  ollama_models:
  qdrant_storage:
